name: RedstoneReinvented
version: @version@
main: me.piggypiglet.redstonereinvented.RedstoneReinvented
author: PiggyPiglet
website: https://piggypiglet.me
commands:
  rr:
    description: "RedstoneReinvented main command."
    aliases: redstonereinvented