name: LogicGateBlocks
version: @version@
main: me.piggypiglet.logicgateblocks.LogicGateBlocks
author: PiggyPiglet
website: https://piggypiglet.me
commands:
  lgb:
    description: "LogicGateBlocks main command."
    aliases: logicgateblocks